# Generated by Django 6.0.6 on 2026-06-22 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('id_rol', models.IntegerField(default=1)),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=100, unique=True)),
                ('contrasena', models.CharField(max_length=255)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('saldo_metrocoins', models.IntegerField(blank=True, default=0, null=True)),
                ('verificado', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.DeleteModel(
            name='Record',
        ),
    ]
